# Accessing/Changing specific elements, rows, columns etc

In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a.shape

(2, 7)

In [7]:
#Get specific elemenent
a[1,5]

13

In [8]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [30]:
# Getting a little more fancy [start index:end index:stepsize]
a[0, 1:6]

array([2, 3, 4, 5, 6])

In [31]:
a[:,1:6]

array([[ 2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13]])

In [32]:
a[0, 1:6:2]

array([2, 4, 6])

In [34]:
a[0, 1:-1:2]

array([2, 4, 6])

In [37]:
a[1,5]=20
print (a)

a[:,2]=5
print (a)

a[:,2]=[1,2]
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
b=np.array([[[1,2], [3,4]], [[5,6],[7,8]]])

In [42]:
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
b[0,1,1]

4

In [44]:
b[1,1,0]

7

In [45]:
#Replace
b[:,1,:]=[[9,9], [8,8]]

In [46]:
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [47]:
c=np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [48]:
print (c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
c[:,2]=20

In [50]:
print (c)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]
