In [1]:
import numpy as np

# The Basics

In [2]:
a=  np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b=np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])

In [5]:
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [12]:
c=np.array([1,2,3], dtype='int16')

In [13]:
c.dtype 

dtype('int16')

In [14]:
a.itemsize

4

In [15]:
b.itemsize

8

In [16]:
a.nbytes

12

In [17]:
a.size*a.itemsize

12

In [18]:
b.nbytes

48

In [19]:
d=np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]])
print (d)

[[1. 2. 3.]
 [3. 4. 5.]]
