In [1]:
import numpy as np

### Be careful when copying arrays!!!

In [6]:
a= np.array([1,2,3])
print (a)
b=a
print (b)
b[0]= 10
print (b)
print (a)

[1 2 3]
[1 2 3]
[10  2  3]
[10  2  3]


In [8]:
a= np.array([1,2,3])
print (a)
b=a.copy()
print (b)
b[0]= 10
print (b)
print (a)

[1 2 3]
[1 2 3]
[10  2  3]
[1 2 3]


In [10]:
a= np.array ([1,2,3,4,5])
b=a
b[2] = 20
print (a)

[ 1  2 20  4  5]


In [11]:
print (b)

[ 1  2 20  4  5]
