In [2]:
import numpy as np

In [3]:
# All 0s matrix
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
# Any other number
np.full ((2,2,2), 99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [8]:
a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
import random

In [17]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.85153115, 0.66139399],
       [0.50534464, 0.37104971],
       [0.64524042, 0.95831326],
       [0.60172767, 0.60640853]])

In [19]:
np.random.random_sample(a.shape)

array([[0.37499411, 0.65725187, 0.23949732, 0.58957091, 0.10636447,
        0.1009636 , 0.74911755],
       [0.39471485, 0.34825899, 0.90737003, 0.95240031, 0.76874513,
        0.70637706, 0.68672689]])

In [27]:
# Random integer values

np.random.randint(4,7, size=(3,3))

array([[4, 4, 5],
       [4, 4, 6],
       [4, 4, 6]])

In [28]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# Repeat arrays; columns
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print (r1)

[[1 1 1 2 2 2 3 3 3]]


In [33]:
# Repeat arrays, rows
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
