In [1]:
import sys
import numpy as np

# Basic Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0,2,-1]]

array([0., 1., 2.])

In [12]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

# Dimensions and Shapes

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [31]:
A.shape

(2, 3)

In [32]:
A.size

6

In [34]:
A.ndim

2

In [35]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [37]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [38]:
B.shape

(2, 2, 3)

In [39]:
B.ndim

3

In [40]:
B.size

12

# Indexing and Slicing of Matrices

In [41]:
# Square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [42]:
A[1]

array([4, 5, 6])

In [43]:
A[1][0]

4

In [44]:
A[1,0]

4

In [45]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
A[1] = np.array([10,10,10])

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [52]:
A[2]=99

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [77]:
a1 = np.array([1,2,3,4])

In [80]:
a1.sum()

10

In [81]:
a1.mean()

2.5

In [82]:
a1.std()

1.118033988749895

In [83]:
a1.var()

1.25

In [86]:
A1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [89]:
A1.sum()

45

In [90]:
A1.mean()

5.0

In [91]:
A1.std()

2.581988897471611

In [92]:
A1.sum(axis=0)

array([12, 15, 18])

In [93]:
A1.sum(axis=1)

array([ 6, 15, 24])

In [94]:
A1.mean(axis=0)

array([4., 5., 6.])

In [95]:
A1.mean(axis=1)

array([2., 5., 8.])

In [96]:
A1.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [97]:
A1.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [98]:
A1.var(axis=0)

array([6., 6., 6.])

In [99]:
A1.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

# Broadcasting and vectorized Operations

In [106]:
a = np.arange(4)

In [107]:
a

array([0, 1, 2, 3])

In [102]:
a + 10

array([10, 11, 12, 13])

In [108]:
a*10

array([ 0, 10, 20, 30])

In [109]:
a

array([0, 1, 2, 3])

In [110]:
a +=100

In [112]:
a

array([100, 101, 102, 103])

In [113]:
a = np.arange(4)

In [114]:
a

array([0, 1, 2, 3])

In [115]:
b = np.array([10,10,10,10])

In [116]:
b

array([10, 10, 10, 10])

In [117]:
a + b

array([10, 11, 12, 13])

In [119]:
a*b

array([100, 100, 100, 100])

# Boolean arrays

In [135]:
a=np.arange(4)

In [136]:
a

array([0, 1, 2, 3])

In [137]:
a[[0, -1]]

array([0, 3])

In [138]:
a[[True, False, False, True]]

array([0, 3])

In [139]:
a>=2

array([False, False,  True,  True])

In [140]:
a[a>=2]

array([2, 3])

In [141]:
a.mean()

1.5

In [143]:
a[a>a.mean()]

array([2, 3])

In [145]:
a[a<a.mean()]

array([0, 1])

In [146]:
a[(a==0) | (a==1)]

array([0, 1])

In [148]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [158]:
A = np.random.randint(100, size=(3,3))

In [159]:
A

array([[46, 39, 62],
       [40, 99, 90],
       [70, 16, 78]])

In [160]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([46, 62, 99, 70, 78])

In [161]:
A >30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [165]:
A[A>30]

array([46, 39, 62, 40, 99, 90, 70, 78])

In [167]:
A[(A==40) | (A==46)]

array([46, 40])

# Linear Algebra

In [178]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [179]:
B= np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [180]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [181]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [182]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [183]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [162]:
D = np.random.randint(100, size=(3,3))

In [163]:
D

array([[49, 88, 23],
       [ 7, 45, 45],
       [74, 15, 43]])

In [164]:
D>=20

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])