# Size of Objects in Memory

# Int, floats

In [3]:
import numpy as np
import sys

# An integer in Python is >24 bytes

In [4]:
sys.getsizeof(1)

28

In [8]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [6]:
#Numpy size is much smaller
np.dtype(int).itemsize

4

In [10]:
#Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [7]:
np.dtype(float).itemsize

8

# Lists are even larger

In [11]:
# A one element list

In [13]:
sys.getsizeof([1])

64

In [15]:
# An array of one element in numpy
np.array([1]).nbytes

4

# And performance is also important

In [21]:
l= list(range(100000))

In [22]:
a = np.arange(100000)

In [23]:
%time np.sum(a**2)

Wall time: 1 ms


216474736

In [24]:
%time sum([x**2 for x in l])

Wall time: 45 ms


333328333350000

# Useful Numpy Operations

# random

In [25]:
np.random.random(size=2)

array([0.20303721, 0.85439506])

In [26]:
np.random.normal(size=2)

array([ 1.43688269, -0.28853774])

In [27]:
np.random.rand(2, 4)

array([[0.70595731, 0.61054828, 0.23569688, 0.89921948],
       [0.16301698, 0.22765996, 0.3504736 , 0.97881719]])

# arange

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [30]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# reshape

In [31]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Linspace

In [33]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [35]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# Zeros, ones, empty

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros((3, 3), dtype=np.int)

C:\Users\DELL\AppData\Local\Temp/ipykernel_184/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# identity and eye

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [51]:
"Hello World"[6]

'W'