In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.20.3


# Array creation
 Create a numpy array of size 10, filled with zeros.

In [3]:
np.array ([0] *10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Create a numpy array with values ranging from 10 to 49

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Create a numpy matrix of 2*2 integers, filled with ones

In [11]:
np.ones ((2,2))

array([[1., 1.],
       [1., 1.]])

# Create a numpy matrix of 3*2 float numbers, filled with ones.

In [17]:
np.ones ((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [21]:
X = np.arange(4)

np.ones_like(X)

array([1, 1, 1, 1])

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [23]:
X = np.array([[1,2,3], [4,5,6]])

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

# Create a numpy matrix of 4*4 integers, filled with fives.

In [30]:
np.ones ((4,4)) *5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens

In [32]:
X = np.array([[2,3], [6,2]])

np.ones_like(X) *7

array([[7, 7],
       [7, 7]])

# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere

In [33]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a numpy array, filled with 3 random integer values between 1 and 10.

In [37]:
np.random.randint (10, size=3)

array([8, 1, 5])

# Create a 3*3*3 numpy matrix, filled with random float values.

In [43]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-0.96141444, -1.00443665,  0.05138592],
        [ 1.99782424,  0.15646614,  0.05013456],
        [-0.61850616,  0.78511145, -1.48033025]],

       [[-0.81378931, -2.41780124, -1.44746832],
        [-1.65389188, -0.14518956, -0.482589  ],
        [-1.04433408, -0.10023284, -0.19113466]],

       [[-0.27348982, -0.37786844, -0.43321139],
        [-0.33517008,  0.59678719, -0.52879917],
        [ 0.43806589,  1.17819258,  0.392852  ]]])

# Given the X python list convert it to an Y numpy array

In [44]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


# Given the X numpy array, make a copy and store it on Y.

In [46]:
X = np.array([5,2,3])
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 1658419449072
[5 2 3] 1658419663952


# Create a numpy array with numbers from 1 to 10

In [54]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Create a numpy array with the odd numbers between 1 to 10

In [50]:
np.arange (1,11,2)

array([1, 3, 5, 7, 9])

# Create a numpy array with numbers from 1 to 10, in descending order.

In [51]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [57]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Show the memory size of the given Z numpy matrix

In [58]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# Array indexation

# Given the X numpy array, show it's first element

In [59]:
X = np.array(['A','B','C','D','E'])

X [0]

'A'

# Given the X numpy array, show it's last element

In [60]:
X = np.array(['A','B','C','D','E'])

X [-1]

'E'

# Given the X numpy array, show it's first three elements

In [63]:
X = np.array(['A','B','C','D','E'])

X [:3]

array(['A', 'B', 'C'], dtype='<U1')

# Given the X numpy array, show all middle elements

In [64]:
X = np.array(['A','B','C','D','E'])

X [1:-1]

array(['B', 'C', 'D'], dtype='<U1')

# Given the X numpy array, show the elements in reverse position

In [65]:
X = np.array(['A','B','C','D','E'])

X [::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

# Given the X numpy array, show the elements in an odd position

In [67]:
X = np.array(['A','B','C','D','E'])

X [::2]

array(['A', 'C', 'E'], dtype='<U1')

# Given the X numpy matrix, show the first row elements

In [68]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [0]

array([1, 2, 3, 4])

# Given the X numpy matrix, show the last row elements


In [73]:
X [3]

array([13, 14, 15, 16])

# Given the X numpy matrix, show the first element on first row

In [74]:
X [0, 0]

1

# Given the X numpy matrix, show the last element on last row

In [75]:
X [3, -1]

16

# Given the X numpy matrix, show the middle row elements

In [76]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

# Given the X numpy matrix, show the first two elements on the first two rows

In [79]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [:2, :2]

array([[1, 2],
       [5, 6]])

# Given the X numpy matrix, show the last two elements on the last two rows

In [83]:
X[2:, 2:]

array([[11, 12],
       [15, 16]])

# Array Manipulation

# Convert the given integer numpy array to float

In [86]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)


C:\Users\DELL\AppData\Local\Temp/ipykernel_4500/1161948714.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

# Reverse the given numpy array (first element becomes last)

In [87]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

# Order (sort) the given numpy array

In [88]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

# Given the X numpy array, set the fifth element equal to 1

In [89]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Given the X numpy array, change the 50 with a 40

In [90]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X


array([10, 20, 30, 40])

# Given the X numpy matrix, change the last row with all 1

In [91]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

# Given the X numpy matrix, change the last item on the last row with a 0

In [92]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[3, -1]= np.array(0)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

# Given the X numpy matrix, add 5 to every element

In [94]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Boolean arrays (also called masks)

# Given the X numpy array, make a mask showing negative elements

In [95]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [96]:
X<=0

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

# Given the X numpy array, get the negative elements

In [97]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [100]:
X[X<=0]

array([-1,  0, -4,  0,  0, -9])

# Given the X numpy array, get numbers higher than 5

In [101]:
X[X>5]

array([ 6, 10])

# Given the X numpy array, get numbers higher than the elements mean

In [104]:
X.mean()

0.9

In [106]:
X[X>(X.mean())]

array([ 2,  5,  6, 10])

# Given the X numpy array, get numbers equal to 2 or 10

In [109]:
X[(X==2) | (X==10)]

array([ 2, 10])

# Logic functions
# Given the X numpy array, return True if none of its elements is zero

In [110]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

# Given the X numpy array, return True if any of its elements is zero

In [111]:
X.any()

True

# Summary statistics
# Given the X numpy array, show the sum of its elements

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

In [112]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

# Given the X numpy array, show the mean value of its elements

In [113]:
X.mean()

4.777777777777778

# Given the X numpy matrix, show the sum of its columns

In [114]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

# Given the X numpy matrix, show the mean value of its rows

In [115]:
X.sum(axis=1)

array([10, 26, 42, 58])

# Given the X numpy array, show the max value of its elements

In [116]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10